# Generated by Django 6.1.1 on 2026-10-03 02:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=12, unique=True
                    ),
                ),
                (
                    "cliente_nombre",
                    models.CharField(max_length=150, verbose_name="nombre del cliente"),
                ),
                ("cliente_email", models.EmailField(blank=True, max_length=254)),
                (
                    "cliente_telefono",
                    models.CharField(max_length=30, verbose_name="teléfono"),
                ),
                (
                    "entrega",
                    models.CharField(
                        choices=[
                            ("ENVIO", "Envío a domicilio"),
                            ("RETIRO", "Retiro en el local"),
                        ],
                        default="ENVIO",
                        max_length=10,
                    ),
                ),
                ("direccion", models.CharField(blank=True, max_length=250)),
                ("comuna", models.CharField(blank=True, max_length=80)),
                ("region", models.CharField(blank=True, max_length=80)),
                ("notas", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=0, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("moneda", models.CharField(default="CLP", max_length=5)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente por WhatsApp"),
                            ("CONFIRMADO", "Confirmado"),
                            ("EN_PREPARACION", "En preparación"),
                            ("ENVIADO", "Enviado"),
                            ("ENTREGADO", "Entregado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("whatsapp_enviado_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("confirmado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "pedido",
                "verbose_name_plural": "pedidos",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producto_nombre", models.CharField(max_length=160)),
                ("producto_slug", models.CharField(blank=True, max_length=180)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=0, max_digits=10),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items_pedido",
                        to="catalogo.producto",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pedidos.pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "ítem de pedido",
                "verbose_name_plural": "ítems de pedido",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["estado", "-creado_en"], name="pedidos_ped_estado_ac21e2_idx"
            ),
        ),
    ]
