# Generated by Django 6.1.1 on 2026-10-03 02:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "orden",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Orden en que aparece en el menú (menor primero).",
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=160)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                (
                    "descripcion_corta",
                    models.CharField(
                        help_text="Texto breve que aparece en la tarjeta del producto.",
                        max_length=200,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción completa (material, uso y cuidado).",
                    ),
                ),
                (
                    "notas_aroma",
                    models.CharField(
                        blank=True,
                        help_text="Notas de aroma, por ejemplo: Lavanda · Bergamota · Vainilla",
                        max_length=200,
                    ),
                ),
                (
                    "volumen_ml",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="volumen (ml)"
                    ),
                ),
                (
                    "duracion_horas",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="duración (horas)"
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Precio en CLP con IVA incluido.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1"))
                        ],
                    ),
                ),
                (
                    "precio_anterior",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Precio antes de la promoción (opcional, para mostrar descuento).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="productos/%Y/%m/",
                        verbose_name="imagen",
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=20)),
                ("activo", models.BooleanField(default=True)),
                (
                    "destacado",
                    models.BooleanField(
                        default=False,
                        help_text="Aparece en la portada dentro de 'Destacados'.",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="catalogo.categoria",
                        verbose_name="categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "ordering": ["-destacado", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ImagenProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="productos/%Y/%m/")),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("es_principal", models.BooleanField(default=False)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galeria",
                        to="catalogo.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "imagen de producto",
                "verbose_name_plural": "imágenes de producto",
                "ordering": ["orden", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["activo", "categoria"], name="catalogo_pr_activo_01843d_idx"
            ),
        ),
    ]
